import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useRef, useState } from 'react'



export default function Home() {
  const inputRef = useRef();
  const [emailRes, setEmailRes] = useState(null);

  async function submitHandler(e) {
    e.preventDefault();

    try {
      const res = await axios.get(`/api/verify-email?EMAIL=${inputRef.current.value}`);
      if (res.data.valid) {
        console.log("Yay!");
        setEmailRes(true);
      } else  {
        console.log("Noooo!");
        setEmailRes(false);
      }

    } catch (err) {
      console.log(err);
    }
    
  }


  function emailResRender(res) {
    if (res == true)
      return <p>Valid</p>
    else if (res == false)
      return <p>Invalid</p>
    else
      return <></>
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Free Email Validator</title>
        <meta name="Free email validator" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Make some form */}
        
        <form onSubmit={submitHandler}>
          <input type='email' placeholder='Email' ref={inputRef}></input>
          <button type='submit'>Check</button>
        </form>

        {emailResRender(emailRes)}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
